### ISSUE TITLE
Evernote.download.recipe - Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by Stette** [autopkg/recipes#468]
**Describe the problem**
`Evernote.download.recipe` fails to download Evernote. Get the following error message:

```
Processing Evernote.munki.recipe...
curl: (22) The requested URL returned error: 404

Failed.

The following recipes failed:
    Evernote.munki.recipe
        Error in local.munki.Evernote: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 404

Nothing downloaded, packaged or imported.

```

Has the URL changed _again_?

**Preferences contents**
https://gist.github.com/Stette/f2e2fb006a2f37db15fcc872010d3a4d

**AutoPkg output**
https://gist.github.com/Stette/2f8d7a005e5796130fa353b86b58e774

**Expected behavior**
To download the newest Evernote

**Version (please complete the following information):**
- OS version: 13.4.1
- AutoPkg Version: 2.7.2

**Comment by dhmoore** [comment]
New URL appears to be https://cdn1.evernote.com/boron/mac/public/latest-mac.yml

Current content:
```
version: 10.61.7
files:
  - url: https://cdn1.evernote.com/boron/mac/builds/Evernote-10.61.7-mac-ddl-stage-20230906172504-7ce1624484970f6d58d6cdf56d8a457fb9b0b45e.zip
    sha512: +dlgLrazSiL4Bw8U+5Uv/9AFvoi5o4f4ubwEc3UEPrtZtE4CATA5ZdPm7KidsSSx7m6ZtsayvRwIgU3UYfIEVg==
    size: 263311907
  - url: https://cdn1.evernote.com/boron/mac/builds/Evernote-10.61.7-mac-ddl-stage-20230906172504-7ce1624484970f6d58d6cdf56d8a457fb9b0b45e.dmg
    sha512: udgW6cPHlAe2Jb9wK9W3WFhlbWib4EjZGu/1ew4nCV2d0gyXu50yred7QGPUTZmlBMgtntHQU8JxpF6Srtvw1A==
    size: 272060724
path: https://cdn1.evernote.com/boron/mac/builds/Evernote-10.61.7-mac-ddl-stage-20230906172504-7ce1624484970f6d58d6cdf56d8a457fb9b0b45e.zip
sha512: +dlgLrazSiL4Bw8U+5Uv/9AFvoi5o4f4ubwEc3UEPrtZtE4CATA5ZdPm7KidsSSx7m6ZtsayvRwIgU3UYfIEVg==
releaseDate: '2023-09-07T15:04:52.000Z'
stagingPercentage: 10
```
